# Generated by Django 2.2.4 on 2019-08-26 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Nominal')),
            ],
        ),
        migrations.AddField(
            model_name='nominal',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsa.Provider'),
        ),
    ]
