# Generated by Django 2.2.4 on 2019-09-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsa', '0003_auto_20190901_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
