# Generated by Django 2.2.4 on 2019-09-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsa', '0008_auto_20190907_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
    ]
