# Generated by Django 2.2.4 on 2019-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20190814_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
